theme: minima
title: Computational Musicology
description: >
  Our goal is to promote computational musicology, namely,
  the development and application of computational methods
  for the sake of achieving a better understanding of music.
  
