theme: minima
title: Computational Musicology
author: The Computational Musicology Group
description: >
  Our goal is to promote computational musicology, namely,
  the development and application of computational methods
  for the sake of achieving a better understanding of music.
header_pages:
  - index.md
  - purpose.md
  - journal-club.md
  - resources.md
  - contributing.md
